# Generated by Django 5.1.3 on 2024-11-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('section', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=50)),
            ],
        ),
    ]
