# Generated by Django 5.1.3 on 2024-12-07 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_attendence', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'managed': False},
        ),
    ]
